from __future__ import annotations

import struct
import tempfile
import unittest
from pathlib import Path

from native import packizard_profile as profile


class PackizardProfileTests(unittest.TestCase):
    def test_direct_read_trace_generates_packizard_profile(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            index = root / "ampr_emu.index"
            commands = root / "ampr_commands.bin"
            output = root / "profile.toml"
            report = root / "profile.md"
            metrics = root / "profile.json"

            path = b"/app0/data/asset.bin"
            path_blob = path + b"\0"
            record = profile.IDX_RECORD.pack(0, len(path), 1024 * 1024, 0)
            hash_offset = profile.IDX_HEADER.size + len(record) + len(path_blob)
            header = profile.IDX_HEADER.pack(b"AMPRIDX3", 3, profile.IDX_RECORD.size, 1, len(path_blob), hash_offset, 16, 0)
            index.write_bytes(header + record + path_blob)

            dwords = 5
            w0 = 40 | ((dwords - 1) << 8)
            payload = struct.pack("<IIIII", w0, 65535, 1, 0, 0)
            cmd_header = profile.CMD_HEADER.pack(
                b"AMPRCMD1", 1, profile.CMD_HEADER.size,
                profile.CMD_HEADER.size + len(payload),
                1, 0, 1, 0, 0, 0, len(payload), len(payload), 1, 0, 1, 0, 0, 0,
            )
            commands.write_bytes(cmd_header + payload)

            profile.generate([(commands, index)], "test", output, report, metrics, True)
            text = output.read_text(encoding="utf-8")
            self.assertIn("Generated by Packizard Engine", text)
            self.assertIn('include = ["data/asset.bin"]', text)
            self.assertIn('action = "compress"', text)
            self.assertTrue(report.is_file())
            self.assertTrue(metrics.is_file())


if __name__ == "__main__":
    unittest.main()
